### ISSUE TITLE
color conversion to hsl format causes panic 

### ISSUE THREAD

**Issue by Alexdelia** [JiatLn/color-art#4]
**Describe the bug**
In case of color conversion to `hsl`, the saturation can be wrongly calculated to more than `1.0f64` and then cause `panic` on `unwrap`

**To Reproduce**
```rs
use color_art::Color;

let color = Color::from_rgba(
   41,
   121,
   255,
   1.0
); // color with saturation of 1.0

dbg!(&color);
/*
Color {
    rgb: [
        41.0,
        121.0,
        255.0,
    ],
    alpha: 1.0,
}
*/

color.darken(0.1); // this calls `Color::from_hsl(h, s, l).unwrap()`
// panics `ColorParserError("Saturation must be between 0.0 and 1.0, got 1.0000000000000002")`
```

**Expected behavior**
the call of `darken` should not panic and behave normaly

**Version**
 - color-art = "0.3.6"
 - rustc = "1.72.0" (5680fa18f 2023-08-23)

**Comment by JiatLn** [comment]
thank you for your issue, I fixed it on v0.3.7
