### ISSUE TITLE
Take Alpha into account when doing Color Blending

### ISSUE THREAD

**Issue by Pixaurora** [JiatLn/color-art#6]
**Is your feature request related to a problem? Please describe.**
When using any of the blend modes, alpha is ignored and set to 1.0 when the color is returned.

**Describe the solution you'd like**
It would be nice to be able to have the blend modes apply "less intensely" if the opacity of the source color is lower, i.e. when using Normal, if the source's opacity is 0, the backdrop's color would be unchanged.

After dwelling on this for a bit, I think an acceptable solution could be to use `Color::mix_with` on the source color, mixing with the backdrop color with the weight being based on the differences between their alpha channels (i.e. `source alpha - backdrop alpha`). I'm open to different ideas though!

**Comment by JiatLn** [comment]
thank you for your issue! I fixed it in v0.3.8

**Comment by Pixaurora** [comment]
Thank you!
